Repository UKHomeOffice/hocs-search, pull requests merged in 2023-03, with the labels that each got.

#304 Stop deploying the Opensearch specific search services
  .drone.yml
Labels: major

#306 HOCS-6419: deploy multiple service and consumer to dev
  .drone.yml
  helm/hocs-search-multiple-consumer.yaml
  helm/hocs-search-multiple.yaml
Labels: minor

#308 HOCS-6419: deploy multiple service and consumer to dev
  .drone.yml
  helm/wcs/hocs-search-multiple-consumer.yaml
  helm/wcs/hocs-search-multiple.yaml
Labels: minor

#309 Set downscaler weekend settings
  .drone.yml
  helm/hocs-search-consumer.yaml
  helm/hocs-search-multiple-consumer.yaml
  helm/hocs-search-multiple.yaml
  helm/hocs-search.yaml
Labels: patch

#305 HOCS-6416: amend alias use-case
  src/main/java/uk/gov/digital/ho/hocs/search/client/elasticsearchclient/BaseElasticSearchClient.java
  src/main/java/uk/gov/digital/ho/hocs/search/client/elasticsearchclient/ElasticSearchMultipleClient.java
  src/main/java/uk/gov/digital/ho/hocs/search/client/elasticsearchclient/ElasticSearchSingularClient.java
  src/test/java/uk/gov/digital/ho/hocs/search/client/elasticsearchclient/ElasticSearchMultipleClientTest.java
Labels: minor

#314 HOCS-6462: update multiple search index prefix
  helm/hocs-search-multiple-consumer.yaml
  helm/hocs-search-multiple.yaml
  helm/wcs/hocs-search-multiple-consumer.yaml
  helm/wcs/hocs-search-multiple.yaml
Labels: patch

#313 HOCS-6209: migrate to OpenSearch libraries
  build.gradle
  src/main/java/uk/gov/digital/ho/hocs/search/api/CaseDataService.java
  src/main/java/uk/gov/digital/ho/hocs/search/api/HocsQueryBuilder.java
  src/main/java/uk/gov/digital/ho/hocs/search/api/QueryBuilderHelpers.java
  src/main/java/uk/gov/digital/ho/hocs/search/application/aws/config/elastic/AwsElasticConfiguration.java
  src/main/java/uk/gov/digital/ho/hocs/search/application/aws/config/elastic/LocalElasticConfiguration.java
  src/main/java/uk/gov/digital/ho/hocs/search/client/elasticsearchclient/BaseElasticSearchClient.java
  src/main/java/uk/gov/digital/ho/hocs/search/client/elasticsearchclient/ElasticSearchClient.java
  src/main/java/uk/gov/digital/ho/hocs/search/client/elasticsearchclient/ElasticSearchClientConfiguration.java
  src/main/java/uk/gov/digital/ho/hocs/search/client/elasticsearchclient/ElasticSearchMultipleClient.java
  src/main/java/uk/gov/digital/ho/hocs/search/client/elasticsearchclient/ElasticSearchSingularClient.java
  src/test/java/uk/gov/digital/ho/hocs/search/api/HocsQueryBuilderTest.java
  src/test/java/uk/gov/digital/ho/hocs/search/aws/listeners/integration/CreateSearchTest.java
  src/test/java/uk/gov/digital/ho/hocs/search/client/elasticsearchclient/BaseElasticSearchClientTest.java
  src/test/java/uk/gov/digital/ho/hocs/search/client/elasticsearchclient/ElasticSearchMultipleClientTest.java
  src/test/java/uk/gov/digital/ho/hocs/search/client/elasticsearchclient/ElasticSearchSingularClientTest.java
Labels: minor
